version: '3'
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex-server
    network_mode: host
    volumes:
      - "/mnt/media/config/plex:/config"
      - "/mnt/media/data/plex/transcode:/transcode"
      - "/mnt/media/library/complete/tv:/mdata/tv"
      - "/mnt/media/library/complete/movies:/mdata/movies"
    ports:
      - 32400:32400
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sickchill:latest
    container_name: sickchill
    volumes:
      - "/mnt/media/config/sonarr:/config"
      - "/mnt/media/library/tv:/tv"
    ports:
      - 8081:8081
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - "/mnt/media/config/radarr:/config"
      - "/mnt/media/library/movies:/movies"
    ports:
      - 7878:7878
    restart: unless-stopped

  rtorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent
    ports:
      - 6881:6881/udp
      - 8080:8080
      - 9000:9000
      - 50000:50000
    volumes:
      - "/mnt/media/data/rtorrent:/data"
      - "/mnt/media/downloads:/downloads"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always
