version: '3'

services:
   emby:
      image: emby/embyserver
      container_name: embyserver
      runtime: nvidia # Expose NVIDIA GPUs
      network_mode: host # Enable DLNA and Wake-on-Lan
      environment:
         - UID=1000 # The UID to run emby as (default: 2)
         - GID=100 # The GID to run emby as (default 2)
         - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
         - TZ=America/Halifax
      volumes:
      volumes:
         - /Media/emby/config:/config
         - /Media/library/tv:/tv
         - /Media/library/movies:/movies
      ports:
         - 8096:8096 # HTTP port
         - 8920:8920 # HTTPS port
      devices:
         - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
         - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
      restart: on-failure

  sickchill:
    image: lscr.io/linuxserver/sickchill:latest
    container_name: sickchill
    environment: &env
    - PUID=1000
    - PGID=1000
    - TZ=America/Halifax
    volumes:
      - /Media/downloads/tv:/downloads
      - /Media/library/tv:/tv
    ports:
      - 8081:8081
    restart: unless-stopped
    network_mode: host

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment: *env
    volumes:
      - /Media/radarr:/config
      - /Media/library/movies:/movies #optional
      - /Media/downloads/movies:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    network_mode: host

  rtorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent
    environment: *env
    ports:
      - 6881:6881/udp
      - 8080:8080
      - 8000:8000
      - 9000:9000
      - 50000:50000
    volumes:
      - /Media/rtorrent:/data
      - /Media/downloads:/downloads
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: unless-stopped
    network_mode: host
