services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/***
      - VERSION=docker
      - PLEX_CLAIM=****
    volumes:
      - /media/seedly/config/plex/config:/config
      - /media/seedly/library/tv:/tv
      - /media/seedly/library/movies:/movies
    restart: unless-stopped
  sickchill:
    image: lscr.io/linuxserver/sickchill:latest
    container_name: sickchill
    environment: &env
    - PUID=1000
    - PGID=1000
    - TZ=America/Halifax
    volumes:
      - /media/seedly/downloads/complete/tv:/downloads
      - /media/seedly/library/tv:/tv
    ports:
      - 8082:8081
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment: *env
    volumes:
      - /media/seedly/config/radarr:/config
      - /media/seedly/library/movies:/movies #optional
      - /media/seedly/downloads/complete/movies:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  rtorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent
    environment: *env
    ports:
      - 6881:6881/udp
      - 8080:8080
      - 8000:8000
      - 9000:9000
      - 50000:50000
    volumes:
      - /media/seedly/rtorrent:/data
      - /media/seedly/downloads:/downloads
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: unless-stopped
