version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    environment: &env
    - PUID=1000
    - PGID=1000
    - TZ=America/Halifax
    volumes:
      - /Media/jellyfin/config:/config
      - /Media/jellyfin/cache:/cache
      - /Media/library/tv:/tv
      - /Media/library/movies:/movies
    ports:
      - 8096:8096
    restart: unless-stopped
    network_mode: host

  sickchill:
    image: lscr.io/linuxserver/sickchill:latest
    container_name: sickchill
    environment: &env
    - PUID=1000
    - PGID=1000
    - TZ=America/Halifax
    volumes:
      - /Media/downloads:/downloads
      - /Media/library/tv:/tv
    ports:
      - 8081:8081
    restart: unless-stopped
    network_mode: host

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment: *env
    volumes:
      - /Media/radarr:/config
      - /Media/library/movies:/movies #optional
      - /Media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    network_mode: host

  rtorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent
    environment: *env
    ports:
      - 6881:6881/udp
      - 8080:8080
      - 8000:8000
      - 9000:9000
      - 50000:50000
    volumes:
      - /Media/rtorrent:/data
      - /Media/downloads:/downloads
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: unless-stopped
    network_mode: host
