version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /mnt/media/jellyfin/config:/config
      - /mnt/media/library/tv:/tv
      - /mnt/media/library/movies:/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  sickchill:
    image: lscr.io/linuxserver/sickchill:latest
    container_name: sickchill
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Halifax
    volumes:
      - "/mnt/media/downloads:/downloads"
      - "/mnt/media/library/tv:/tv"
    ports:
      - 8081:8081
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - "/mnt/media/config/radarr:/config"
      - "/mnt/media/library/movies:/movies"
    ports:
      - 7878:7878
    restart: unless-stopped

  rtorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent
    ports:
      - 6881:6881/udp
      - 8080:8080
      - 9000:9000
      - 50000:50000
    volumes:
      - "/mnt/media/data/rtorrent:/data"
      - "/mnt/media/downloads:/downloads"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always
