version: '3'
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex-server
    network_mode: host
    env_file:
      - "stack.env"
    volumes:
      - ./config/plex:/config
      - ./data/plex/transcode:/transcode
      - tv:/mdata/tv
      - movies:/mdata/movies
    ports:
      - 32400:32400
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - "stack.env"
    volumes:
      - ./config/sonarr:/config
      - tv:/tv #optional
      - rtorrent:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - "stack.env"
    volumes:
      - ./config/radarr:/config
      - movies:/movies #optional
      - rtorrent:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  rtorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent
    ports:
      - 6881:6881/udp
      - 8080:8080
      - 9000:9000
      - 50000:50000
    env_file:
      - "stack.env"
    volumes:
      - "./data:/data"
      - "rtorrent:/downloads"
      - "./passwd:/passwd"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always

  muximux:
    image: lscr.io/linuxserver/muximux:latest
    container_name: muximux
    env_file:
      - "stack.env"
    volumes:
      - ./config/muximux:/config
    ports:
      - 9090:80
    restart: unless-stopped

volumes:
  tv:
    external: true
  movies:
    external: true
   rtorrent:
    external: true