version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1005:1005
    volumes:
      - /media/jellyfin/config:/config
      - /media/library/tv:/tv
      - /media/library/movies:/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  sickchill:
    image: lscr.io/linuxserver/sickchill:latest
    container_name: sickchill
    environment:
    - PUID=1005
    - PGID=1005
    - TZ=America/Halifax
    volumes:
      - "/media/downloads:/downloads"
      - "/media/library/tv:/tv"
    ports:
      - 8081:8081
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
    - PUID=1005
    - PGID=1005
    - TZ=America/Halifax
    volumes:
      - "/media/config/radarr:/config"
      - "/media/downloads/complete/movies:/movies"
      - "/media/downloads/complete/radarr:/radarr_movies"
    ports:
      - 7878:7878
    restart: unless-stopped

  rtorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent
    ports:
      - 6881:6881/udp
      - 8080:8080
      - 9000:9000
      - 50000:50000
    volumes:
      - "/media/data/rtorrent:/data"
      - "/media/downloads:/downloads"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always
